### ISSUE TITLE
Please clarify the LICENSE of the project

### ISSUE THREAD

**Issue by dibyendumajumdar** [qtiuto/luaffi#1]
Hi,

Looks like you have made some enhancements to luaffi. I would like to merge your changes in but I am not sure what the License is, please would you add your copyright / License to the sources you have updated?

It would also be good to know if you discovered bugs in the luaffi code that you fixed; I wasn't sure if your changes are bug fixes or enhancements; it seems like you have added the ability to pass structs by value?

Thank you - and keep up the good work!

Regards
Dibyendu

**Comment by qtiuto** [comment]
Licence is added. It may be hard for you to merge changes, good luck.

**Comment by dibyendumajumdar** [comment]
Thank you - I will give it a go.
